# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/
#common-application-properties

# Level for loggers on classes inside the root package "netgloo" (and its
# sub-packages)
# Available levels are: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
logging.level.com.danielpark.ai: DEBUG
server.port: 7129

# Specify the level for spring boot and hibernate's loggers
#logging.level.org.springframework.web = OFF
#logging.level.org.hibernate = OFF

# Log file location (in addition to the console)
#logging.file = /var/daniel_blog/logs/application.log

# DataSource settings: set here your own configurations for the database
# connection. In this example we have "ai" as database name and
# "root" as username and "???" as password.
spring :
  datasource:
    url: jdbc:mysql://112.155.234.31:2103/coin
    username: dot
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
