logging.level.com.danielpark.ai: DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql: true
server.port: 9292
spring :
  datasource:
    url: jdbc:mysql://192.168.219.129:2103/taste
    username: taste
    password: taste
    driver-class-name: com.mysql.jdbc.Driver

    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

elasticsearch:
  server:
    host: 192.168.219.129
    port: 9200
    scheme: http
  index: taste