logging.level.com.danielpark.ai: DEBUG
server.port: ????
spring :
  datasource:
    url: jdbc:mysql://???
    username: ???
    password: ???
    driver-class-name: com.mysql.jdbc.Driver

    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    # properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
